### PR TITLE
Restructure directory for specification documents and update some doc…

### PR DESCRIPTION
**Pull request by mpredli01**
…umentation

This PR sets the initial directory structure for the Jakarta Data documentation.  As documentation files are added, they can easily be placed in a directory that makes sense and referenced accordingly.

### CODE REVIEW

**Review by keilw — DISMISSED** [review]
Why does the header in all those files say
>Copyright (c) 2022 Nathan Rauh, Otavio Santana (project leads)

and not
>Copyright (c) 2022 Contributors to the Eclipse Foundation

like the sources?

Besides as Nathan represents IBM it mustn't say his name but IBM instead, while for Otavio it might be OK. So if there was no problem with the "Committers" version, that seems easier here, too.

**Comment by njr-11** [comment]
> Why does the header in all those files say...

The copyright should not have my name or company name in it.  Copyrights in this pull should be switched to

> Copyright (c) 2022 Contributors to the Eclipse Foundation

as @keilw points out.
That should be a simple change.  Thanks for helping to improve the documentation!

**Comment by mpredli01** [comment]
Oops, sorry about that.  I was going by what was on the Jakarta NoSQL license headers.  Yes, an easy fix indeed!

**Comment by mpredli01** [comment]
Thanks for letting me know...

**Comment by mpredli01** [comment]
@njr-11, @otaviojava, @keilw: The appropriate changes were made.

**Review by njr-11 — APPROVED** [review]

**Review by otaviojava — APPROVED** [review]

**Pull request merged**
