### PR TITLE
OrderBy annotation for sorting

### LINKED ISSUE #18: Could OrderBy be better specified annotatively?
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

have a less lengthy and less error-prone way of defining custom repository methods

...which enables me to:

better understand the code that uses my repository methods and
reduce the opportunity for misspellings and mistakes in my repository methods.

Instead of writing queries such as the following that make the code almost unreadable,

```
List<Employee> findByDepartmentAndIdNotOrderByPositionDescLastNameAscFirstNameAsc(String deptNum, int empNum);

...
coworkers = employees.findByDepartmentAndIdNotOrderByPositionDescLastNameAscFirstNameAsc(deptNum, empNum);
```

suppose we allowed the sorting information to all be declared annotatively,

```
@OrderBy(value = "position", descending = true)
@OrderBy("lastName")
@OrderBy("firstName")
List<Employee> findByDepartmentAndIdNot(String deptNum, int empNum);

...
coworkers = employees.findByDepartmentAndIdNot(deptNum, empNum);
```

The only disadvantage I can think of is if someone wanted to duplicate the exact same query but with different ordering, but it's likely that special case would already be solved by the Sorts parameter that some of the implementations have.

### PR DESCRIPTION
**Pull request by njr-11**
fixes  #18

Signed-off-by: Nathan Rauh <nathan.rauh@us.ibm.com>

### CODE REVIEW

**Comment by otaviojava** [comment]
@njr-11 please, don't forget to add the documentation and this option on the [spec](https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc) as well.

**Review by otaviojava — DISMISSED** [review]

**Comment by otaviojava** [comment]
Anyway, IMHO: it is free to go.

**Comment by njr-11** [comment]
> @njr-11 please, don't forget to add the documentation and this option on the [spec](https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc) as well.

@otaviojava thanks - with #16 now merged, I rebased onto that and added a [commit](https://github.com/jakartaee/data/pull/20/commits/fb8bf5a8b7775ec1944b659494dbe7ee3509ed24) that updates the repository spec document.  It also includes a couple of minor fixes that I spotted (making the indentation of the code examples consistent and a one-word correction) while making the change.

**Comment by otaviojava** [comment]
@njr-11 about the documentation.
IMHO
We should not remove the method by the query that we support.
I would like to add this annotation as an option.
It is mainly on all vendors such as Spring, Micronaut, Delta Spike, JNoSQL. 
It is already a standard.

**Review by otaviojava — APPROVED** [review]

**Pull request merged**
