### PR TITLE
Remove Sortby annotation

### PR DESCRIPTION
**Pull request by otaviojava**
We had an issue discussing this annotation, but it is not clear, even with more documentation, if this annotation is proper.

So, 

- I propose removing it.
- Incentive to a vendor implement a feature like that, then move again to this discussion with a case. 

Ref: https://github.com/jakartaee/data/issues/94

### CODE REVIEW

**Comment by keilw** [comment]
Let's see, what vendor/implementor reps like @graemerocher (for Micronaut) say, if they don't see a value at this point, then let'S remove it.

**Comment by otaviojava** [comment]
@keilw, you have the discussion here:
https://github.com/jakartaee/data/issues/94

**Review by njr-11 — CHANGES_REQUESTED** [review]
This matter was discussed in #94 and agreement was never reached on removing it, so there should not be a pull to do so.  As I pointed out there, if anything is to be removed for sorting, this is the wrong thing to remove.  In the various tests that I have been writing for Jakarta Data thus far, I have found this annotation to be extremely useful and much preferred over the lengthy method names with the `OrderBy`/`Asc`/`Desc` keywords such as `repo.findBySomethingGreaterThanEqualAndSomethngElseLessThanOrderBySomethingAscSomethingElseAscAnotherThingAsc(something, somethingElse);` so if anything is to be removed, my vote is for the latter, not the annotation.   I'm also fine with leaving things as is and keeping both for the sake of compatibility with existing solutions.  Additional reasons are discussed in #94 - I can't copy all of that here.

It also needs to be pointed out that even if this change were to be agreed upon, it is not correct as written and introduces errors into the spec in at least one place.

**Comment by otaviojava** [comment]
@njr-11 I closed.

Sorry for my misunderstanding

**Pull request closed without merging**
