### PR TITLE
Include a note about no mix types of query in a single one

### PR DESCRIPTION
**Pull request by otaviojava**
Changes

# Fixes https://github.com/jakartaee/data/issues/732

### CODE REVIEW

**Review by njr-11 — APPROVED** [review]
This is consistent with the `@Query` JavaDoc, which states:
```
 * <p>A given query must not mix named and ordinal parameters.</p>
```

**Comment by gavinking** [comment]
@otaviojava this is the wrong section, that section is supposed to be the lexical structure.

**Comment by gavinking** [comment]
You could put it in 5.3.3, for example.

**Comment by otaviojava** [comment]
> You could put it in 5.3.3, for example.

done

**Pull request merged**
