### PR TITLE
accessor method to obtain EntityManager

### LINKED ISSUE #202: Obtaining the EntityManager (or NoSQL equivalents) for a repository
The following pattern was discussed/proposed in the Jakarta Data Meeting on August 2nd:

```
@MyQualifier
@PersistenceContext(unitName = "MyPersistenceUnit")
@Produces
EntityManager entityMgr;

void dispose(@Disposes @MyQualifier EntityManager em) {
    em.close();
}

...

public interface Cars extends CrudRepository<Car, Integer> {
    default void someAdvancedOperation(int param1, int param2) {
        EntityManager em = CDI.current().select(EntityManager.class, MyQualifier.Literal.instance()).get();
        ... Use the entity manager for advanced JPA operations
    }
}
```

I later realized there is a problem with it in that it relies on the Jakarta Data user to supply the JPA configuration and corresponding EntityManager in the first place.  Some providers might externalize things this way, but Jakarta Data intentionally does not require it (by request of one of the providers and I also agree with them) because other JPA-based Jakarta Data providers might generate all of the JPA related stuff internally.  A spec solution to obtaining the entity manager (and other similar resources if NoSQL) needs to be something that will work for all providers.

It turns out there's a solution to obtaining underlying resources that is already in Jakarta EE and Java SE.

In Jakarta Persistence (JPA) you can invoke an unwrap method on an EntityManager to obtain the underlying resources that it uses, such as the java.sql.Connection,
```
    Connection connection = entityManager.unwrap(Connection.class);
```

Similarly, there is also an unwrap on several JDBC interfaces, such as,
```
    OracleConnection oc = connection.unwrap(OracleConnection.class);
```

We could continue this pattern to be able to obtain the underlying EntityManager for a repository with,
```
     EntityManager em = myRepository.unwrap(EntityManager.class);
```

which could be used from a default method:
```
public interface Cars extends CrudRepository<Car, Integer> {
    default void someAdvancedOperation(int param1, int param2) {
        try (EntityManager em = unwrap(EntityManager.class)) {
            ... Use the entity manager for advanced JPA operations
        }
    }
}
```

If we do this, we would need to decide whether to add the unwrap method to the base DataRepository interface, or to a separate mix-in interface (we would need a name for it).

@otaviojava 
@georgleber

### PR DESCRIPTION
**Pull request by njr-11**
Write up the approach for obtaining the EntityManager/DataSource/Connection that was discussed and decided upon during the Jakarta Data call.
fixes #202

### CODE REVIEW

**Review by otaviojava — APPROVED** [review]

**Comment by otaviojava** [comment]
Way better, thank you.
I loved this approach.

**Comment by keilw** [comment]
@njr-11  @otaviojava Why did that PR merge all sorts of HTML code into the `module-info`?
Was there a mix-up between files? I don't see how all of those aspects are relevant for the module-info/JPMS.

**Comment by njr-11** [comment]
> @njr-11 @otaviojava Why did that PR merge all sorts of HTML code into the `module-info`? Was there a mix-up between files? I don't see how all of those aspects are relevant for the module-info/JPMS.

This information is included there as the main entry point for JavaDoc that developers will refer to when using Jakarta Data.  Note that if you go to the Jakarta EE page for the Jakarta Data spec, https://jakarta.ee/specifications/data/1.0/
and then scroll to the section where it links to the JavaDoc, "Jakarta Data 1.0 Specification Javadoc", this link, https://jakarta.ee/specifications/data/1.0/apidocs, goes directly to the page that is created by module-info.  At least this is how it works by default.  Let us know if there is some other convention/approach for Jakarta specs to have a different JavaDoc page be the entry point.  The information here is extremely important for developers as their primary reference and entry point for using Jakarta Data.  Typical users never read the spec document (although the spec document is very useful for Jakarta Data providers and very advanced users).  Most users will rely on JavaDoc alone.

**Comment by keilw** [comment]
Ok, so that's a bit like the one for JShell: https://docs.oracle.com/javase/9/docs/api/jdk.jshell-summary.html

Btw, I think the "api" in the module name should not be included, All others I checked including REST or Persistence don't include it.

**Pull request merged**
