### PR TITLE
fix  {@code } inside <pre>

### LINKED ISSUE #661: [Bug]: use of {@code } inside <pre>
### Specification Version

1.0.0-M3

### Bug report

The latest update to IntelliJ renders `{@code }` inside `<pre>` even worse than before, so we need to fix all the javadoc.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gavinking**
fixes #661

### CODE REVIEW

**Review by njr-11 — APPROVED** [review]
Approving, but it's sad to see our work of switching to `{@code}` to make the source more readable being undone.

**Comment by gavinking** [comment]
We could use `@snippet`.

**Comment by gavinking** [comment]
(I'm not sure if you've seen how it renders in the latest IntelliJ update, so I'm attaching a screenshot.)
Screenshot 2024-04-05 at 6 56 31 PM

**Comment by njr-11** [comment]
> We could use `@snippet`.

Yes, let's plan to do that next version or whatever version we don't need to still support Java 17.
For now, let's just get this merged. It is already potentially conflicting with other JavaDoc fixes I've made locally, although I think one of them with PageRequest you already covered under this.

**Comment by gavinking** [comment]
> For now, let's just get this merged. 

OK I will merge it now.

**Pull request merged**
