### PR TITLE
Release version 1.0.0-b1

### PR DESCRIPTION
**Pull request by otaviojava**
This PR creates a release version to 1.0.0-b1.

As we discussed, the first release primarily aims to receive feedback from the community and see some implementations/vendor feedback.

### CODE REVIEW

**Comment by mpredli01** [comment]
Hi @otaviojava:

Everything looks good to me!  Let's see what the Java community has to say.

Mike.

**Comment by otaviojava** [comment]
@mpredli01 could you approve then?

**Comment by pzygielo** [comment]
So - there is a plan to merge this to master and keep the fixed version there instead of next SNAPSHOT? Shouldn't this version be rather set by build job instead?
It looks that https://ci.eclipse.org/data/job/jakarta-data-deploy/ is at least timer-based and it deploys current `main`. It's 1.0.0-SNAPSHOT so far. If this PR gets merged as-is, next deployments will happen for 1.0.0-b1 version.

It doesn't seem right to me.

**Review by mpredli01 — APPROVED** [review]
Approved!

**Review by njr-11 — COMMENTED** [review]
In git email notifications, I see that @pzygielo raised a concern about versioning in this pull, but I can't see it anywhere on the pull itself.  Other than that, having a beta/alpha at this point seems like a good idea.

**Comment by otaviojava** [comment]
I agree with @njr-11 and @pzygielo 
We'll move it forward, but it would be fantastic if we fix it to the following versions.

**Comment by pzygielo** [comment]
Is there a plan to deal with failures https://ci.eclipse.org/data/job/jakarta-data-deploy/32/console?

**Comment by otaviojava** [comment]
Hey @pzygielo yes.

We cannot publish twice a non-snapshot version on Maven.

We have this issue with releasing and then returning to snapshot after the release:

https://github.com/jakartaee/data/issues/104

**Comment by pzygielo** [comment]
> We cannot publish twice a non-snapshot version on Maven.

I know, I've already told that here 5 days ago.

> We have this issue with releasing and then returning to snapshot after the release:
> - #104

I believe setting version back to 1.0.0-SNAPSHOT could be done manually, couldn't it?

**Pull request merged**
