### PR TITLE
Replacing assertion libraries: Hamcrest by AssertJ

### PR DESCRIPTION
**Pull request by eliasnogueira**
### Motivation

This PR replace Hamcrest assertion library by AssertJ to add more fluent asserts.

### Changed

- jakarta-data-api
    - Removed `hamcrest-all` in favour of `assertj-core`
    - Changed the assertions in `PageableTest` and `SortTest`
    - Removed redundant tests on `SortTest`
- jakarta-data-parent
    - Updated the following libraries
        - `mockito`.version` to `4.8.0`
        - `junit` to `5.9.0`
    - Fix typo on `mockito.version`

### CODE REVIEW

**Comment by otaviojava** [comment]
Thank you @eliasnogueira it sounds good to go.

@njr-11 What do you think?
could you review it?

**Comment by njr-11** [comment]
> @njr-11 What do you think?
> could you review it?

This looks like it is primarily a change to how the unit tests are styled, which can be a matter of preference between developers.  I don't have a preference here and would lean toward whatever is the standard or convention for Jakarta specs, if there even is one.  I really have no idea.  The changes themselves look valid.  The intent of the tests has been preserved and I don't see any coverage lost or added.  It certainly makes sense at this point in the development cycle at the very beginning of the project to decide on what the standard will be for tests because now is when it's easiest to convert what is there.

**Review by otaviojava — APPROVED** [review]

**Review by njr-11 — APPROVED** [review]
Earlier this week I posted to the Jakarta Data mailing list to check if anyone was opposed to switching the style of test assertions and there were no objections, so I think we can merge this.

**Comment by eliasnogueira** [comment]
@otaviojava @njr-11 I pulled the latest changes from `main` adding the new test (page size) and additional checks from the exception check test.

Could you please review it?

**Review by njr-11 — APPROVED** [review]

**Pull request merged**
