### PR TITLE
Create a JPA domain

### PR DESCRIPTION
**Pull request by otaviojava**
JPA is a universe, and IMHO, having a unique domain in Jakarta Data makes sense.

I propose to have the JPA specialization and start to address these issues in this JPA specialization.

- https://github.com/jakartaee/data/issues/224
- https://github.com/jakartaee/data/issues/225

If it is okay, we can merge and request help from the Hibernate team to enhance those points.

### CODE REVIEW

**Comment by graemerocher** [comment]
Doesn't this belong in the JPA spec if it adopts this spec?

**Comment by otaviojava** [comment]
IMHO: Yes, that would be the perfect world where the spec team could address those issues better than us.

However, they may not want this approach.

I can put those behaviors on this JPA domain inside Jakarta Data.


But let's see what the other people think about it:

@gavinking @njr-11

**Comment by gavinking** [comment]
So, look, "repositories" were first suggested as a feature for JPA on 2020, and so [back in 2021](https://github.com/jakartaee/persistence/issues/294#issuecomment-985054093) I responded that it didn't belong in the Persistence spec and that people who were interested should try it to write a separate spec, and that comment lead directly to the creation of the Jakarta Data project. And so here we are.

And so far my personal opinion hasn't changed at all: Jakarta Persistence is a self-contained API and doesn't require the use of "repositories", neither Jakarta Data repositories, nor any other sort of repository. @lukasj might very well have a different take, so naturally I'll let him speak for himself.

And at present it's completely unclear that Jakarta Data in its final form will be even _appropriate_ for use as a wrapper around Jakarta Persistence. In #229 there was extreme hostility to even _discussing_ the implementation difficulties and conceptual mismatches which arise here. Now, I do actually believe that it's _conceptually possible_ to evolve the Jakarta Data spec in a direction which would make a JPA-backed implementation _feasible_. But that will take work, and some time, and is certainly not yet a done deal.

And look, OK, please let me be a bit direct about this. If you folks hope for such a thing to ever happen, you'll have to work with JPA experts, and refrain from yelling at us when we talk about Jakarta Persistence in this issue tracker. If folks here continue with this _"get lost with your Jakarta Persistence concerns, we don't care about Jakarta Persistence here"_ attitude, in quite clear evidence on that other thread, then I'll let you guess what the inevitable outcome of that is going to be.

So no, in summary, there's a whole lot of work to be done here before we could even _contemplate_ adding anything Jakarta Data-related to the Persistence spec.

**Review by njr-11 — CHANGES_REQUESTED** [review]
This interface doesn't have any methods on it or documentation. I realize your intent is probably to get things done in stages, which in general is a good approach, but let's not introduce a JpaRepository subinterface until we have decided to add at least one repository operation that is unique to Jakarta Persistence that could not also apply to JDBC or any other type of database.  We would also need to consider naming it something other than JPA which is owned by Oracle for Java EE.  Once we have an idea of what methods would belong on it, it might become clearer what to call it.

**Comment by otaviojava** [comment]
@njr-11 What I had in my mind is with this specialization, answer those two issues:

- https://github.com/jakartaee/data/issues/224
- https://github.com/jakartaee/data/issues/225

What do you have in your mind? Only using the spec side?

**Comment by njr-11** [comment]
> @njr-11 What I had in my mind is with this specialization, answer those two issues:
> 
>     *

225 is more general than JPA.  Note that Gavin also mentions `DataSource` and `Connection` which are JDBC.  There are ideas for solving this which have been discussed thus far which do not require a JPA-specific repository.

224 is an area that needs work for sure, and it is most likely to be what defines JPA-specific repository operations.  It remains to be determined whether that will be defined in a more general sense or very specific to JPA.  In either case, we should let the work that develops out of that determine how an additional repository sub interface gets defined and what best to name it.

**Comment by otaviojava** [comment]
So, I will close this PR for while.

**Comment by keilw** [comment]
Good idea, I would not rush into this, until it is clear, if spec wording is enough, or indeed some JPA integration was needed, and where.

I am not so actively involved in the Jakarta REST project other than the platform or Spec Committee, but it could be worth looking into the [changes since 2.1](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1#changes-since-2.1-release) especially how optional support for XML/JAXB is handled there.

The use case is somewhat similar, not forcing users and implementers of the spec to support both:
- JSON
- XML

If they only ever need one.

**Pull request closed without merging**
